name: Main-CI

on:
  push:
    branches: [ master ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - run: npm install

      - name: Build
      - run: npm run build
#      - run: git config --global user.name ${{secrets.GH_NAME}}
#      - run: git config --global user.email ${{secrets.GH_EMAIL}}
#      - run: git remote set-url origin https://${{secrets.GH_ACCESS_TOKEN}}@github.com/${{secrets.GH_USERNAME}}/ridiculously-over-engineered-calculator.git
#      - run: npm run deploy-ghp
        env:
          CI: true

