name: Main-CI

on:
  push:
    branches: [ master ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'
      - run: yarn
      - run: git config --global user.name ${{secrets.GH_NAME}}
      - run: git config --global user.email ${{secrets.GH_EMAIL}}
      - run: git remote set-url origin https://${{secrets.GH_ACCESS_TOKEN}}@github.com/${{secrets.GH_USERNAME}}/silvamuller-rocks.git
      - run: yarn build
      - run: yarn deploy
        env:
          CI: true
          NODE_ENV: 'prod'

